// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/cloudxyzi.proto

#ifndef PROTOBUF_sensor_2fcloudxyzi_2eproto__INCLUDED
#define PROTOBUF_sensor_2fcloudxyzi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/header.pb.h"
// @@protoc_insertion_point(includes)

namespace SensorMsg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_sensor_2fcloudxyzi_2eproto();
void protobuf_AssignDesc_sensor_2fcloudxyzi_2eproto();
void protobuf_ShutdownFile_sensor_2fcloudxyzi_2eproto();

class PointCloudXYZI;
class PointXYZI;

// ===================================================================

class PointXYZI : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SensorMsg.PointXYZI) */ {
 public:
  PointXYZI();
  virtual ~PointXYZI();

  PointXYZI(const PointXYZI& from);

  inline PointXYZI& operator=(const PointXYZI& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PointXYZI& default_instance();

  void Swap(PointXYZI* other);

  // implements Message ----------------------------------------------

  inline PointXYZI* New() const { return New(NULL); }

  PointXYZI* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PointXYZI& from);
  void MergeFrom(const PointXYZI& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PointXYZI* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // optional uint32 intensity = 4;
  void clear_intensity();
  static const int kIntensityFieldNumber = 4;
  ::google::protobuf::uint32 intensity() const;
  void set_intensity(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SensorMsg.PointXYZI)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float x_;
  float y_;
  float z_;
  ::google::protobuf::uint32 intensity_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sensor_2fcloudxyzi_2eproto();
  friend void protobuf_AssignDesc_sensor_2fcloudxyzi_2eproto();
  friend void protobuf_ShutdownFile_sensor_2fcloudxyzi_2eproto();

  void InitAsDefaultInstance();
  static PointXYZI* default_instance_;
};
// -------------------------------------------------------------------

class PointCloudXYZI : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SensorMsg.PointCloudXYZI) */ {
 public:
  PointCloudXYZI();
  virtual ~PointCloudXYZI();

  PointCloudXYZI(const PointCloudXYZI& from);

  inline PointCloudXYZI& operator=(const PointCloudXYZI& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PointCloudXYZI& default_instance();

  void Swap(PointCloudXYZI* other);

  // implements Message ----------------------------------------------

  inline PointCloudXYZI* New() const { return New(NULL); }

  PointCloudXYZI* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PointCloudXYZI& from);
  void MergeFrom(const PointCloudXYZI& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PointCloudXYZI* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CommonMsg.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::CommonMsg::Header& header() const;
  ::CommonMsg::Header* mutable_header();
  ::CommonMsg::Header* release_header();
  void set_allocated_header(::CommonMsg::Header* header);

  // optional int32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // optional int32 height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // optional bool is_dense = 4;
  void clear_is_dense();
  static const int kIsDenseFieldNumber = 4;
  bool is_dense() const;
  void set_is_dense(bool value);

  // repeated .SensorMsg.PointXYZI points = 5;
  int points_size() const;
  void clear_points();
  static const int kPointsFieldNumber = 5;
  const ::SensorMsg::PointXYZI& points(int index) const;
  ::SensorMsg::PointXYZI* mutable_points(int index);
  ::SensorMsg::PointXYZI* add_points();
  ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZI >*
      mutable_points();
  const ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZI >&
      points() const;

  // @@protoc_insertion_point(class_scope:SensorMsg.PointCloudXYZI)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::CommonMsg::Header* header_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZI > points_;
  bool is_dense_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sensor_2fcloudxyzi_2eproto();
  friend void protobuf_AssignDesc_sensor_2fcloudxyzi_2eproto();
  friend void protobuf_ShutdownFile_sensor_2fcloudxyzi_2eproto();

  void InitAsDefaultInstance();
  static PointCloudXYZI* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PointXYZI

// optional float x = 1;
inline void PointXYZI::clear_x() {
  x_ = 0;
}
inline float PointXYZI::x() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZI.x)
  return x_;
}
inline void PointXYZI::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZI.x)
}

// optional float y = 2;
inline void PointXYZI::clear_y() {
  y_ = 0;
}
inline float PointXYZI::y() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZI.y)
  return y_;
}
inline void PointXYZI::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZI.y)
}

// optional float z = 3;
inline void PointXYZI::clear_z() {
  z_ = 0;
}
inline float PointXYZI::z() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZI.z)
  return z_;
}
inline void PointXYZI::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZI.z)
}

// optional uint32 intensity = 4;
inline void PointXYZI::clear_intensity() {
  intensity_ = 0u;
}
inline ::google::protobuf::uint32 PointXYZI::intensity() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZI.intensity)
  return intensity_;
}
inline void PointXYZI::set_intensity(::google::protobuf::uint32 value) {
  
  intensity_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZI.intensity)
}

// -------------------------------------------------------------------

// PointCloudXYZI

// optional .CommonMsg.Header header = 1;
inline bool PointCloudXYZI::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
inline void PointCloudXYZI::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
inline const ::CommonMsg::Header& PointCloudXYZI::header() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZI.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::CommonMsg::Header* PointCloudXYZI::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::CommonMsg::Header;
  }
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZI.header)
  return header_;
}
inline ::CommonMsg::Header* PointCloudXYZI::release_header() {
  // @@protoc_insertion_point(field_release:SensorMsg.PointCloudXYZI.header)
  
  ::CommonMsg::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void PointCloudXYZI::set_allocated_header(::CommonMsg::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SensorMsg.PointCloudXYZI.header)
}

// optional int32 width = 2;
inline void PointCloudXYZI::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 PointCloudXYZI::width() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZI.width)
  return width_;
}
inline void PointCloudXYZI::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZI.width)
}

// optional int32 height = 3;
inline void PointCloudXYZI::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 PointCloudXYZI::height() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZI.height)
  return height_;
}
inline void PointCloudXYZI::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZI.height)
}

// optional bool is_dense = 4;
inline void PointCloudXYZI::clear_is_dense() {
  is_dense_ = false;
}
inline bool PointCloudXYZI::is_dense() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZI.is_dense)
  return is_dense_;
}
inline void PointCloudXYZI::set_is_dense(bool value) {
  
  is_dense_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZI.is_dense)
}

// repeated .SensorMsg.PointXYZI points = 5;
inline int PointCloudXYZI::points_size() const {
  return points_.size();
}
inline void PointCloudXYZI::clear_points() {
  points_.Clear();
}
inline const ::SensorMsg::PointXYZI& PointCloudXYZI::points(int index) const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZI.points)
  return points_.Get(index);
}
inline ::SensorMsg::PointXYZI* PointCloudXYZI::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZI.points)
  return points_.Mutable(index);
}
inline ::SensorMsg::PointXYZI* PointCloudXYZI::add_points() {
  // @@protoc_insertion_point(field_add:SensorMsg.PointCloudXYZI.points)
  return points_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZI >*
PointCloudXYZI::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:SensorMsg.PointCloudXYZI.points)
  return &points_;
}
inline const ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZI >&
PointCloudXYZI::points() const {
  // @@protoc_insertion_point(field_list:SensorMsg.PointCloudXYZI.points)
  return points_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SensorMsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sensor_2fcloudxyzi_2eproto__INCLUDED
