// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/cloudxyz.proto

#ifndef PROTOBUF_sensor_2fcloudxyz_2eproto__INCLUDED
#define PROTOBUF_sensor_2fcloudxyz_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/header.pb.h"
// @@protoc_insertion_point(includes)

namespace SensorMsg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
void protobuf_AssignDesc_sensor_2fcloudxyz_2eproto();
void protobuf_ShutdownFile_sensor_2fcloudxyz_2eproto();

class PointCloudXYZ;
class PointXYZ;

// ===================================================================

class PointXYZ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SensorMsg.PointXYZ) */ {
 public:
  PointXYZ();
  virtual ~PointXYZ();

  PointXYZ(const PointXYZ& from);

  inline PointXYZ& operator=(const PointXYZ& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PointXYZ& default_instance();

  void Swap(PointXYZ* other);

  // implements Message ----------------------------------------------

  inline PointXYZ* New() const { return New(NULL); }

  PointXYZ* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PointXYZ& from);
  void MergeFrom(const PointXYZ& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PointXYZ* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:SensorMsg.PointXYZ)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float x_;
  float y_;
  float z_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  friend void protobuf_AssignDesc_sensor_2fcloudxyz_2eproto();
  friend void protobuf_ShutdownFile_sensor_2fcloudxyz_2eproto();

  void InitAsDefaultInstance();
  static PointXYZ* default_instance_;
};
// -------------------------------------------------------------------

class PointCloudXYZ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SensorMsg.PointCloudXYZ) */ {
 public:
  PointCloudXYZ();
  virtual ~PointCloudXYZ();

  PointCloudXYZ(const PointCloudXYZ& from);

  inline PointCloudXYZ& operator=(const PointCloudXYZ& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PointCloudXYZ& default_instance();

  void Swap(PointCloudXYZ* other);

  // implements Message ----------------------------------------------

  inline PointCloudXYZ* New() const { return New(NULL); }

  PointCloudXYZ* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PointCloudXYZ& from);
  void MergeFrom(const PointCloudXYZ& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PointCloudXYZ* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CommonMsg.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::CommonMsg::Header& header() const;
  ::CommonMsg::Header* mutable_header();
  ::CommonMsg::Header* release_header();
  void set_allocated_header(::CommonMsg::Header* header);

  // optional int32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // optional int32 height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // optional bool is_dense = 4;
  void clear_is_dense();
  static const int kIsDenseFieldNumber = 4;
  bool is_dense() const;
  void set_is_dense(bool value);

  // repeated .SensorMsg.PointXYZ points = 5;
  int points_size() const;
  void clear_points();
  static const int kPointsFieldNumber = 5;
  const ::SensorMsg::PointXYZ& points(int index) const;
  ::SensorMsg::PointXYZ* mutable_points(int index);
  ::SensorMsg::PointXYZ* add_points();
  ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ >*
      mutable_points();
  const ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ >&
      points() const;

  // @@protoc_insertion_point(class_scope:SensorMsg.PointCloudXYZ)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::CommonMsg::Header* header_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ > points_;
  bool is_dense_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  friend void protobuf_AssignDesc_sensor_2fcloudxyz_2eproto();
  friend void protobuf_ShutdownFile_sensor_2fcloudxyz_2eproto();

  void InitAsDefaultInstance();
  static PointCloudXYZ* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PointXYZ

// optional float x = 1;
inline void PointXYZ::clear_x() {
  x_ = 0;
}
inline float PointXYZ::x() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZ.x)
  return x_;
}
inline void PointXYZ::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZ.x)
}

// optional float y = 2;
inline void PointXYZ::clear_y() {
  y_ = 0;
}
inline float PointXYZ::y() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZ.y)
  return y_;
}
inline void PointXYZ::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZ.y)
}

// optional float z = 3;
inline void PointXYZ::clear_z() {
  z_ = 0;
}
inline float PointXYZ::z() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZ.z)
  return z_;
}
inline void PointXYZ::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZ.z)
}

// -------------------------------------------------------------------

// PointCloudXYZ

// optional .CommonMsg.Header header = 1;
inline bool PointCloudXYZ::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
inline void PointCloudXYZ::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
inline const ::CommonMsg::Header& PointCloudXYZ::header() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::CommonMsg::Header* PointCloudXYZ::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::CommonMsg::Header;
  }
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZ.header)
  return header_;
}
inline ::CommonMsg::Header* PointCloudXYZ::release_header() {
  // @@protoc_insertion_point(field_release:SensorMsg.PointCloudXYZ.header)
  
  ::CommonMsg::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void PointCloudXYZ::set_allocated_header(::CommonMsg::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SensorMsg.PointCloudXYZ.header)
}

// optional int32 width = 2;
inline void PointCloudXYZ::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 PointCloudXYZ::width() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.width)
  return width_;
}
inline void PointCloudXYZ::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZ.width)
}

// optional int32 height = 3;
inline void PointCloudXYZ::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 PointCloudXYZ::height() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.height)
  return height_;
}
inline void PointCloudXYZ::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZ.height)
}

// optional bool is_dense = 4;
inline void PointCloudXYZ::clear_is_dense() {
  is_dense_ = false;
}
inline bool PointCloudXYZ::is_dense() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.is_dense)
  return is_dense_;
}
inline void PointCloudXYZ::set_is_dense(bool value) {
  
  is_dense_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZ.is_dense)
}

// repeated .SensorMsg.PointXYZ points = 5;
inline int PointCloudXYZ::points_size() const {
  return points_.size();
}
inline void PointCloudXYZ::clear_points() {
  points_.Clear();
}
inline const ::SensorMsg::PointXYZ& PointCloudXYZ::points(int index) const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.points)
  return points_.Get(index);
}
inline ::SensorMsg::PointXYZ* PointCloudXYZ::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZ.points)
  return points_.Mutable(index);
}
inline ::SensorMsg::PointXYZ* PointCloudXYZ::add_points() {
  // @@protoc_insertion_point(field_add:SensorMsg.PointCloudXYZ.points)
  return points_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ >*
PointCloudXYZ::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:SensorMsg.PointCloudXYZ.points)
  return &points_;
}
inline const ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ >&
PointCloudXYZ::points() const {
  // @@protoc_insertion_point(field_list:SensorMsg.PointCloudXYZ.points)
  return points_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SensorMsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sensor_2fcloudxyz_2eproto__INCLUDED
