// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/cloudxyz.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sensor/cloudxyz.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SensorMsg {

namespace {

const ::google::protobuf::Descriptor* PointXYZ_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PointXYZ_reflection_ = NULL;
const ::google::protobuf::Descriptor* PointCloudXYZ_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PointCloudXYZ_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sensor_2fcloudxyz_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_sensor_2fcloudxyz_2eproto() {
  protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sensor/cloudxyz.proto");
  GOOGLE_CHECK(file != NULL);
  PointXYZ_descriptor_ = file->message_type(0);
  static const int PointXYZ_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZ, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZ, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZ, z_),
  };
  PointXYZ_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PointXYZ_descriptor_,
      PointXYZ::default_instance_,
      PointXYZ_offsets_,
      -1,
      -1,
      -1,
      sizeof(PointXYZ),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZ, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZ, _is_default_instance_));
  PointCloudXYZ_descriptor_ = file->message_type(1);
  static const int PointCloudXYZ_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, is_dense_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, points_),
  };
  PointCloudXYZ_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PointCloudXYZ_descriptor_,
      PointCloudXYZ::default_instance_,
      PointCloudXYZ_offsets_,
      -1,
      -1,
      -1,
      sizeof(PointCloudXYZ),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZ, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sensor_2fcloudxyz_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PointXYZ_descriptor_, &PointXYZ::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PointCloudXYZ_descriptor_, &PointCloudXYZ::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sensor_2fcloudxyz_2eproto() {
  delete PointXYZ::default_instance_;
  delete PointXYZ_reflection_;
  delete PointCloudXYZ::default_instance_;
  delete PointCloudXYZ_reflection_;
}

void protobuf_AddDesc_sensor_2fcloudxyz_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_sensor_2fcloudxyz_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::CommonMsg::protobuf_AddDesc_common_2fheader_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025sensor/cloudxyz.proto\022\tSensorMsg\032\023comm"
    "on/header.proto\"+\n\010PointXYZ\022\t\n\001x\030\001 \001(\002\022\t"
    "\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"\210\001\n\rPointCloudXYZ\022!"
    "\n\006header\030\001 \001(\0132\021.CommonMsg.Header\022\r\n\005wid"
    "th\030\002 \001(\005\022\016\n\006height\030\003 \001(\005\022\020\n\010is_dense\030\004 \001"
    "(\010\022#\n\006points\030\005 \003(\0132\023.SensorMsg.PointXYZb"
    "\006proto3", 247);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sensor/cloudxyz.proto", &protobuf_RegisterTypes);
  PointXYZ::default_instance_ = new PointXYZ();
  PointCloudXYZ::default_instance_ = new PointCloudXYZ();
  PointXYZ::default_instance_->InitAsDefaultInstance();
  PointCloudXYZ::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sensor_2fcloudxyz_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sensor_2fcloudxyz_2eproto {
  StaticDescriptorInitializer_sensor_2fcloudxyz_2eproto() {
    protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  }
} static_descriptor_initializer_sensor_2fcloudxyz_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PointXYZ::kXFieldNumber;
const int PointXYZ::kYFieldNumber;
const int PointXYZ::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PointXYZ::PointXYZ()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SensorMsg.PointXYZ)
}

void PointXYZ::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PointXYZ::PointXYZ(const PointXYZ& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SensorMsg.PointXYZ)
}

void PointXYZ::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
}

PointXYZ::~PointXYZ() {
  // @@protoc_insertion_point(destructor:SensorMsg.PointXYZ)
  SharedDtor();
}

void PointXYZ::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PointXYZ::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PointXYZ::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PointXYZ_descriptor_;
}

const PointXYZ& PointXYZ::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  return *default_instance_;
}

PointXYZ* PointXYZ::default_instance_ = NULL;

PointXYZ* PointXYZ::New(::google::protobuf::Arena* arena) const {
  PointXYZ* n = new PointXYZ;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PointXYZ::Clear() {
// @@protoc_insertion_point(message_clear_start:SensorMsg.PointXYZ)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PointXYZ, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PointXYZ*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, z_);

#undef ZR_HELPER_
#undef ZR_

}

bool PointXYZ::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SensorMsg.PointXYZ)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float x = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_y;
        break;
      }

      // optional float y = 2;
      case 2: {
        if (tag == 21) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_z;
        break;
      }

      // optional float z = 3;
      case 3: {
        if (tag == 29) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SensorMsg.PointXYZ)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SensorMsg.PointXYZ)
  return false;
#undef DO_
}

void PointXYZ::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SensorMsg.PointXYZ)
  // optional float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  // @@protoc_insertion_point(serialize_end:SensorMsg.PointXYZ)
}

::google::protobuf::uint8* PointXYZ::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SensorMsg.PointXYZ)
  // optional float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SensorMsg.PointXYZ)
  return target;
}

int PointXYZ::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SensorMsg.PointXYZ)
  int total_size = 0;

  // optional float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // optional float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // optional float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PointXYZ::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SensorMsg.PointXYZ)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PointXYZ* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PointXYZ>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SensorMsg.PointXYZ)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SensorMsg.PointXYZ)
    MergeFrom(*source);
  }
}

void PointXYZ::MergeFrom(const PointXYZ& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SensorMsg.PointXYZ)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void PointXYZ::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SensorMsg.PointXYZ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointXYZ::CopyFrom(const PointXYZ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SensorMsg.PointXYZ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointXYZ::IsInitialized() const {

  return true;
}

void PointXYZ::Swap(PointXYZ* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PointXYZ::InternalSwap(PointXYZ* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PointXYZ::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PointXYZ_descriptor_;
  metadata.reflection = PointXYZ_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PointXYZ

// optional float x = 1;
void PointXYZ::clear_x() {
  x_ = 0;
}
 float PointXYZ::x() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZ.x)
  return x_;
}
 void PointXYZ::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZ.x)
}

// optional float y = 2;
void PointXYZ::clear_y() {
  y_ = 0;
}
 float PointXYZ::y() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZ.y)
  return y_;
}
 void PointXYZ::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZ.y)
}

// optional float z = 3;
void PointXYZ::clear_z() {
  z_ = 0;
}
 float PointXYZ::z() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZ.z)
  return z_;
}
 void PointXYZ::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZ.z)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PointCloudXYZ::kHeaderFieldNumber;
const int PointCloudXYZ::kWidthFieldNumber;
const int PointCloudXYZ::kHeightFieldNumber;
const int PointCloudXYZ::kIsDenseFieldNumber;
const int PointCloudXYZ::kPointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PointCloudXYZ::PointCloudXYZ()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SensorMsg.PointCloudXYZ)
}

void PointCloudXYZ::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  header_ = const_cast< ::CommonMsg::Header*>(&::CommonMsg::Header::default_instance());
}

PointCloudXYZ::PointCloudXYZ(const PointCloudXYZ& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SensorMsg.PointCloudXYZ)
}

void PointCloudXYZ::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  header_ = NULL;
  width_ = 0;
  height_ = 0;
  is_dense_ = false;
}

PointCloudXYZ::~PointCloudXYZ() {
  // @@protoc_insertion_point(destructor:SensorMsg.PointCloudXYZ)
  SharedDtor();
}

void PointCloudXYZ::SharedDtor() {
  if (this != default_instance_) {
    delete header_;
  }
}

void PointCloudXYZ::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PointCloudXYZ::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PointCloudXYZ_descriptor_;
}

const PointCloudXYZ& PointCloudXYZ::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  return *default_instance_;
}

PointCloudXYZ* PointCloudXYZ::default_instance_ = NULL;

PointCloudXYZ* PointCloudXYZ::New(::google::protobuf::Arena* arena) const {
  PointCloudXYZ* n = new PointCloudXYZ;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PointCloudXYZ::Clear() {
// @@protoc_insertion_point(message_clear_start:SensorMsg.PointCloudXYZ)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PointCloudXYZ, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PointCloudXYZ*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(width_, height_);
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
  is_dense_ = false;

#undef ZR_HELPER_
#undef ZR_

  points_.Clear();
}

bool PointCloudXYZ::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SensorMsg.PointCloudXYZ)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CommonMsg.Header header = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_width;
        break;
      }

      // optional int32 width = 2;
      case 2: {
        if (tag == 16) {
         parse_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_height;
        break;
      }

      // optional int32 height = 3;
      case 3: {
        if (tag == 24) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_is_dense;
        break;
      }

      // optional bool is_dense = 4;
      case 4: {
        if (tag == 32) {
         parse_is_dense:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_dense_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_points;
        break;
      }

      // repeated .SensorMsg.PointXYZ points = 5;
      case 5: {
        if (tag == 42) {
         parse_points:
          DO_(input->IncrementRecursionDepth());
         parse_loop_points:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_points()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_loop_points;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SensorMsg.PointCloudXYZ)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SensorMsg.PointCloudXYZ)
  return false;
#undef DO_
}

void PointCloudXYZ::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SensorMsg.PointCloudXYZ)
  // optional .CommonMsg.Header header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->header_, output);
  }

  // optional int32 width = 2;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->width(), output);
  }

  // optional int32 height = 3;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->height(), output);
  }

  // optional bool is_dense = 4;
  if (this->is_dense() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->is_dense(), output);
  }

  // repeated .SensorMsg.PointXYZ points = 5;
  for (unsigned int i = 0, n = this->points_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->points(i), output);
  }

  // @@protoc_insertion_point(serialize_end:SensorMsg.PointCloudXYZ)
}

::google::protobuf::uint8* PointCloudXYZ::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SensorMsg.PointCloudXYZ)
  // optional .CommonMsg.Header header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->header_, false, target);
  }

  // optional int32 width = 2;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->width(), target);
  }

  // optional int32 height = 3;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->height(), target);
  }

  // optional bool is_dense = 4;
  if (this->is_dense() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->is_dense(), target);
  }

  // repeated .SensorMsg.PointXYZ points = 5;
  for (unsigned int i = 0, n = this->points_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, this->points(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SensorMsg.PointCloudXYZ)
  return target;
}

int PointCloudXYZ::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SensorMsg.PointCloudXYZ)
  int total_size = 0;

  // optional .CommonMsg.Header header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->header_);
  }

  // optional int32 width = 2;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  // optional int32 height = 3;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  // optional bool is_dense = 4;
  if (this->is_dense() != 0) {
    total_size += 1 + 1;
  }

  // repeated .SensorMsg.PointXYZ points = 5;
  total_size += 1 * this->points_size();
  for (int i = 0; i < this->points_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->points(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PointCloudXYZ::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SensorMsg.PointCloudXYZ)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PointCloudXYZ* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PointCloudXYZ>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SensorMsg.PointCloudXYZ)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SensorMsg.PointCloudXYZ)
    MergeFrom(*source);
  }
}

void PointCloudXYZ::MergeFrom(const PointCloudXYZ& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SensorMsg.PointCloudXYZ)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  points_.MergeFrom(from.points_);
  if (from.has_header()) {
    mutable_header()->::CommonMsg::Header::MergeFrom(from.header());
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.is_dense() != 0) {
    set_is_dense(from.is_dense());
  }
}

void PointCloudXYZ::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SensorMsg.PointCloudXYZ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointCloudXYZ::CopyFrom(const PointCloudXYZ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SensorMsg.PointCloudXYZ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointCloudXYZ::IsInitialized() const {

  return true;
}

void PointCloudXYZ::Swap(PointCloudXYZ* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PointCloudXYZ::InternalSwap(PointCloudXYZ* other) {
  std::swap(header_, other->header_);
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(is_dense_, other->is_dense_);
  points_.UnsafeArenaSwap(&other->points_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PointCloudXYZ::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PointCloudXYZ_descriptor_;
  metadata.reflection = PointCloudXYZ_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PointCloudXYZ

// optional .CommonMsg.Header header = 1;
bool PointCloudXYZ::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
void PointCloudXYZ::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
const ::CommonMsg::Header& PointCloudXYZ::header() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
::CommonMsg::Header* PointCloudXYZ::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::CommonMsg::Header;
  }
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZ.header)
  return header_;
}
::CommonMsg::Header* PointCloudXYZ::release_header() {
  // @@protoc_insertion_point(field_release:SensorMsg.PointCloudXYZ.header)
  
  ::CommonMsg::Header* temp = header_;
  header_ = NULL;
  return temp;
}
void PointCloudXYZ::set_allocated_header(::CommonMsg::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SensorMsg.PointCloudXYZ.header)
}

// optional int32 width = 2;
void PointCloudXYZ::clear_width() {
  width_ = 0;
}
 ::google::protobuf::int32 PointCloudXYZ::width() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.width)
  return width_;
}
 void PointCloudXYZ::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZ.width)
}

// optional int32 height = 3;
void PointCloudXYZ::clear_height() {
  height_ = 0;
}
 ::google::protobuf::int32 PointCloudXYZ::height() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.height)
  return height_;
}
 void PointCloudXYZ::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZ.height)
}

// optional bool is_dense = 4;
void PointCloudXYZ::clear_is_dense() {
  is_dense_ = false;
}
 bool PointCloudXYZ::is_dense() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.is_dense)
  return is_dense_;
}
 void PointCloudXYZ::set_is_dense(bool value) {
  
  is_dense_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZ.is_dense)
}

// repeated .SensorMsg.PointXYZ points = 5;
int PointCloudXYZ::points_size() const {
  return points_.size();
}
void PointCloudXYZ::clear_points() {
  points_.Clear();
}
const ::SensorMsg::PointXYZ& PointCloudXYZ::points(int index) const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZ.points)
  return points_.Get(index);
}
::SensorMsg::PointXYZ* PointCloudXYZ::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZ.points)
  return points_.Mutable(index);
}
::SensorMsg::PointXYZ* PointCloudXYZ::add_points() {
  // @@protoc_insertion_point(field_add:SensorMsg.PointCloudXYZ.points)
  return points_.Add();
}
::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ >*
PointCloudXYZ::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:SensorMsg.PointCloudXYZ.points)
  return &points_;
}
const ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZ >&
PointCloudXYZ::points() const {
  // @@protoc_insertion_point(field_list:SensorMsg.PointCloudXYZ.points)
  return points_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace SensorMsg

// @@protoc_insertion_point(global_scope)
