// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/cloud_common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sensor/cloud_common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SensorMsg {

namespace {


}  // namespace


void protobuf_AssignDesc_sensor_2fcloud_5fcommon_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_sensor_2fcloud_5fcommon_2eproto() {
  protobuf_AddDesc_sensor_2fcloud_5fcommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sensor/cloud_common.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sensor_2fcloud_5fcommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_sensor_2fcloud_5fcommon_2eproto() {
}

void protobuf_AddDesc_sensor_2fcloud_5fcommon_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_sensor_2fcloud_5fcommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::SensorMsg::protobuf_AddDesc_sensor_2fcloudxyz_2eproto();
  ::SensorMsg::protobuf_AddDesc_sensor_2fcloudxyzi_2eproto();
  ::SensorMsg::protobuf_AddDesc_sensor_2fcloudxyzit_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031sensor/cloud_common.proto\022\tSensorMsg\032\025"
    "sensor/cloudxyz.proto\032\026sensor/cloudxyzi."
    "proto\032\027sensor/cloudxyzit.protob\006proto3", 118);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sensor/cloud_common.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sensor_2fcloud_5fcommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sensor_2fcloud_5fcommon_2eproto {
  StaticDescriptorInitializer_sensor_2fcloud_5fcommon_2eproto() {
    protobuf_AddDesc_sensor_2fcloud_5fcommon_2eproto();
  }
} static_descriptor_initializer_sensor_2fcloud_5fcommon_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace SensorMsg

// @@protoc_insertion_point(global_scope)
