// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/image.proto

#ifndef PROTOBUF_sensor_2fimage_2eproto__INCLUDED
#define PROTOBUF_sensor_2fimage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/header.pb.h"
// @@protoc_insertion_point(includes)

namespace SensorMsg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_sensor_2fimage_2eproto();
void protobuf_AssignDesc_sensor_2fimage_2eproto();
void protobuf_ShutdownFile_sensor_2fimage_2eproto();

class Image;

// ===================================================================

class Image : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SensorMsg.Image) */ {
 public:
  Image();
  virtual ~Image();

  Image(const Image& from);

  inline Image& operator=(const Image& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Image& default_instance();

  void Swap(Image* other);

  // implements Message ----------------------------------------------

  inline Image* New() const { return New(NULL); }

  Image* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Image& from);
  void MergeFrom(const Image& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Image* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CommonMsg.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::CommonMsg::Header& header() const;
  ::CommonMsg::Header* mutable_header();
  ::CommonMsg::Header* release_header();
  void set_allocated_header(::CommonMsg::Header* header);

  // optional int32 rows = 2;
  void clear_rows();
  static const int kRowsFieldNumber = 2;
  ::google::protobuf::int32 rows() const;
  void set_rows(::google::protobuf::int32 value);

  // optional int32 cols = 3;
  void clear_cols();
  static const int kColsFieldNumber = 3;
  ::google::protobuf::int32 cols() const;
  void set_cols(::google::protobuf::int32 value);

  // optional int32 elt_type = 4;
  void clear_elt_type();
  static const int kEltTypeFieldNumber = 4;
  ::google::protobuf::int32 elt_type() const;
  void set_elt_type(::google::protobuf::int32 value);

  // optional bytes mat_data = 5;
  void clear_mat_data();
  static const int kMatDataFieldNumber = 5;
  const ::std::string& mat_data() const;
  void set_mat_data(const ::std::string& value);
  void set_mat_data(const char* value);
  void set_mat_data(const void* value, size_t size);
  ::std::string* mutable_mat_data();
  ::std::string* release_mat_data();
  void set_allocated_mat_data(::std::string* mat_data);

  // @@protoc_insertion_point(class_scope:SensorMsg.Image)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::CommonMsg::Header* header_;
  ::google::protobuf::int32 rows_;
  ::google::protobuf::int32 cols_;
  ::google::protobuf::internal::ArenaStringPtr mat_data_;
  ::google::protobuf::int32 elt_type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sensor_2fimage_2eproto();
  friend void protobuf_AssignDesc_sensor_2fimage_2eproto();
  friend void protobuf_ShutdownFile_sensor_2fimage_2eproto();

  void InitAsDefaultInstance();
  static Image* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Image

// optional .CommonMsg.Header header = 1;
inline bool Image::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
inline void Image::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
inline const ::CommonMsg::Header& Image::header() const {
  // @@protoc_insertion_point(field_get:SensorMsg.Image.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::CommonMsg::Header* Image::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::CommonMsg::Header;
  }
  // @@protoc_insertion_point(field_mutable:SensorMsg.Image.header)
  return header_;
}
inline ::CommonMsg::Header* Image::release_header() {
  // @@protoc_insertion_point(field_release:SensorMsg.Image.header)
  
  ::CommonMsg::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Image::set_allocated_header(::CommonMsg::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SensorMsg.Image.header)
}

// optional int32 rows = 2;
inline void Image::clear_rows() {
  rows_ = 0;
}
inline ::google::protobuf::int32 Image::rows() const {
  // @@protoc_insertion_point(field_get:SensorMsg.Image.rows)
  return rows_;
}
inline void Image::set_rows(::google::protobuf::int32 value) {
  
  rows_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.Image.rows)
}

// optional int32 cols = 3;
inline void Image::clear_cols() {
  cols_ = 0;
}
inline ::google::protobuf::int32 Image::cols() const {
  // @@protoc_insertion_point(field_get:SensorMsg.Image.cols)
  return cols_;
}
inline void Image::set_cols(::google::protobuf::int32 value) {
  
  cols_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.Image.cols)
}

// optional int32 elt_type = 4;
inline void Image::clear_elt_type() {
  elt_type_ = 0;
}
inline ::google::protobuf::int32 Image::elt_type() const {
  // @@protoc_insertion_point(field_get:SensorMsg.Image.elt_type)
  return elt_type_;
}
inline void Image::set_elt_type(::google::protobuf::int32 value) {
  
  elt_type_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.Image.elt_type)
}

// optional bytes mat_data = 5;
inline void Image::clear_mat_data() {
  mat_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Image::mat_data() const {
  // @@protoc_insertion_point(field_get:SensorMsg.Image.mat_data)
  return mat_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Image::set_mat_data(const ::std::string& value) {
  
  mat_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SensorMsg.Image.mat_data)
}
inline void Image::set_mat_data(const char* value) {
  
  mat_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SensorMsg.Image.mat_data)
}
inline void Image::set_mat_data(const void* value, size_t size) {
  
  mat_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SensorMsg.Image.mat_data)
}
inline ::std::string* Image::mutable_mat_data() {
  
  // @@protoc_insertion_point(field_mutable:SensorMsg.Image.mat_data)
  return mat_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Image::release_mat_data() {
  // @@protoc_insertion_point(field_release:SensorMsg.Image.mat_data)
  
  return mat_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Image::set_allocated_mat_data(::std::string* mat_data) {
  if (mat_data != NULL) {
    
  } else {
    
  }
  mat_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mat_data);
  // @@protoc_insertion_point(field_set_allocated:SensorMsg.Image.mat_data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace SensorMsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sensor_2fimage_2eproto__INCLUDED
